/**
 * The ensemble judge: N independent runs per (page, eval), each a fresh
 * request with no shared context (eval isolation), aggregated by consensus
 * and routed through confidence zones. Persisted human reviews resolve
 * needs-review outcomes for unchanged pages.
 *
 * The ensemble mechanics — retry-once, errored runs counting against
 * consensus, cache replay — live in `@hawkeyexl/inference` (ADR 01002). What
 * stays here is moose-docevals' own orchestration: the bounded-concurrency pool
 * across targets, the cost budget, the self-judgment warning, and human-review
 * resolution.
 */
import {
  JsonCache,
  computeConsensus,
  costOfRuns,
  pricingFor,
  runEnsemble,
  zoneFor,
  type InferenceProvider,
  type JudgeRun,
} from "@hawkeyexl/inference";
import verdictSchemaJson from "./verdict-schema.json" with { type: "json" };
import type { EvalResult } from "../types.js";
import type { DocevalsConfig } from "../core/config.js";
import type { JudgeFn, JudgeOptions } from "../core/engine.js";
import type { GraderTarget } from "../graders/types.js";
import { findReview, loadReviews } from "../core/reviews.js";
import { cacheKey } from "./cache.js";
import { JUDGE_SYSTEM_PROMPT, buildUserContent } from "./prompt.js";
import { providerSpecFor } from "./provider.js";
import { resolve as resolvePath } from "node:path";

/**
 * moose-docevals' own verdict wording. Structurally identical to the library's
 * canonical schema, but the field descriptions talk about pages rather than
 * generic subjects — and descriptions are prompt surface that steers the
 * model, so they are worth keeping (the inference library's own ADR 01001,
 * not this repo's).
 */
const verdictSchema = verdictSchemaJson as Record<string, unknown>;

export interface JudgeStageDeps {
  provider: InferenceProvider;
  root: string;
}

/** Build the engine's judge stage around a concrete provider. */
export function makeJudge(deps: JudgeStageDeps): JudgeFn {
  return async (
    targets: GraderTarget[],
    config: DocevalsConfig,
    options: JudgeOptions,
  ): Promise<EvalResult[]> => {
    const { provider, root } = deps;
    const runsPerEval = options.runs ?? config.judge.ensembleRuns;
    const temperature = config.judge.temperature;
    const cache = new JsonCache<JudgeRun[]>(
      resolvePath(root, config.judge.cacheDir),
      options.noCache !== true,
      "moose-docevals",
    );
    // Pricing overrides ride on the provider spec, so the same mapping that
    // builds the provider also answers what its model costs.
    const pricing = pricingFor(
      provider.modelName(),
      providerSpecFor(config, options).pricing,
    );
    const reviews = loadReviews(root);
    const maxCostUsd = options.maxCostUsd ?? config.judge.maxCostUsd;
    let spentUsd = 0;

    const results: EvalResult[] = [];
    const concurrency = config.defaults.concurrency;
    let index = 0;

    // Safeguard layer 1: a model judging its own output shows self-preference
    // bias, so warn when a page declares it was generated by the judge model.
    const selfJudged = new Set<string>();
    for (const t of targets) {
      const by = t.plan.generatedBy;
      if (by && by === provider.modelName() && !selfJudged.has(by)) {
        selfJudged.add(by);
        console.warn(
          `moose-docevals: ${t.plan.page.file} declares generatedBy: ${by}, which is also the judge model. A model judging its own output favors it — judge with a different model.`,
        );
      }
    }

    const judgeTarget = async (target: GraderTarget): Promise<EvalResult> => {
      const { plan, eval: ev } = target;
      const start = Date.now();
      if (maxCostUsd != null && spentUsd >= maxCostUsd) {
        return {
          evalName: ev.name,
          type: ev.type,
          grader: ev.grader,
          file: plan.page.file,
          outcome: "skipped",
          skipReason: `judge cost budget exhausted ($${maxCostUsd})`,
          durationMs: 0,
        };
      }

      const runs = await runEnsemble({
        provider,
        system: JUDGE_SYSTEM_PROMPT,
        user: buildUserContent(ev, plan.page.body),
        runs: runsPerEval,
        temperature,
        schema: verdictSchema,
        cache,
        cacheKey: cacheKey(
          provider.provider(),
          provider.modelName(),
          runsPerEval,
          temperature,
          plan.page.body,
          ev,
        ),
        label: "moose-docevals",
      });

      const consensusBase = computeConsensus(runs);
      const zone = zoneFor(consensusBase, config.judge.zones);
      const consensus = { ...consensusBase, zone };
      const costUsd = costOfRuns(runs, pricing);
      spentUsd += costUsd;

      let outcome: EvalResult["outcome"] =
        zone === "auto-pass" ? "pass" : zone === "auto-fail" ? "fail" : "needs-review";
      let via: EvalResult["via"];
      if (outcome === "needs-review") {
        const review = findReview(reviews, plan.page.file, ev.name, plan.page.body);
        if (review) {
          outcome = review.verdict;
          via = "human-review";
        }
      }

      return {
        evalName: ev.name,
        type: ev.type,
        grader: ev.grader,
        file: plan.page.file,
        outcome,
        consensus,
        via,
        costUsd,
        durationMs: Date.now() - start,
      };
    };

    // Simple bounded-concurrency pool across targets; runs within one eval
    // stay sequential (independent requests, no shared context).
    const workers = Array.from(
      { length: Math.min(concurrency, targets.length) },
      async () => {
        while (index < targets.length) {
          const i = index++;
          results[i] = await judgeTarget(targets[i]!);
        }
      },
    );
    await Promise.all(workers);
    return results;
  };
}
